# Generated by Django 4.2.9 on 2024-02-01 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hull_id', models.CharField(max_length=40)),
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marina.boat')),
            ],
        ),
        migrations.CreateModel(
            name='BoatLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_num', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
