# Generated by Django 4.2.9 on 2024-02-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0003_remove_boatspace_renter_alter_boatspace_boat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='name',
            new_name='boat_name',
        ),
    ]
