# Generated by Django 4.2.9 on 2024-02-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0004_rename_name_boat_boat_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoatRegistration',
        ),
    ]
