# Generated by Django 4.2.9 on 2024-02-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0005_delete_boatregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatspace',
            name='reserve_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boatspace',
            name='reserve_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
