# Generated by Django 4.2.9 on 2024-02-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0006_alter_boatspace_reserve_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_valid_insurance',
        ),
    ]
